name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build all platforms
        run: |
          VERSION=${{ steps.version.outputs.VERSION }} make build-all-platforms

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.tar.gz
          body: |
            ## reghost ${{ steps.version.outputs.VERSION }}
            
            A lightweight DNS server daemon with dynamic configuration management for local development.
            
            ### Quick Install
            
            **macOS (Apple Silicon):**
            ```bash
            curl -L https://github.com/bilgehannal/reghost/releases/download/${{ steps.version.outputs.VERSION }}/reghost-darwin-arm64.tar.gz | sudo tar -xz -C /usr/local/bin && sudo chmod 6755 /usr/local/bin/reghost{d,ctl} && sudo chgrp admin /usr/local/bin/reghost{d,ctl}
            ```
            
            **macOS (Intel):**
            ```bash
            curl -L https://github.com/bilgehannal/reghost/releases/download/${{ steps.version.outputs.VERSION }}/reghost-darwin-amd64.tar.gz | sudo tar -xz -C /usr/local/bin && sudo chmod 6755 /usr/local/bin/reghost{d,ctl} && sudo chgrp admin /usr/local/bin/reghost{d,ctl}
            ```
            
            **Linux (x64):**
            ```bash
            curl -L https://github.com/bilgehannal/reghost/releases/download/${{ steps.version.outputs.VERSION }}/reghost-linux-amd64.tar.gz | sudo tar -xz -C /usr/local/bin && sudo chmod 6755 /usr/local/bin/reghost{d,ctl} && sudo chgrp root /usr/local/bin/reghost{d,ctl}
            ```
            
            **Linux (ARM64):**
            ```bash
            curl -L https://github.com/bilgehannal/reghost/releases/download/${{ steps.version.outputs.VERSION }}/reghost-linux-arm64.tar.gz | sudo tar -xz -C /usr/local/bin && sudo chmod 6755 /usr/local/bin/reghost{d,ctl} && sudo chgrp root /usr/local/bin/reghost{d,ctl}
            ```
            
            ### Getting Started
            
            1. Start the daemon:
               ```bash
               reghostd
               ```
            
            2. Add a DNS record:
               ```bash
               reghostctl add-record default --domain myapp.local --ip 192.168.1.100
               ```
            
            3. Test it:
               ```bash
               ping myapp.local
               ```
            
            ### What's Changed
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
